apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: spring-music
  name: spring-music
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spring-music
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spring-music
        app.kubernetes.io/part-of: spring-music
    spec:
      containers:
      - image: <REGISTRY>/spring-music:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
        name: app
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
        env:
          - name: SPRING_DATA_MONGODB_HOST
            value: music-mongodb
          - name: SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE
            value: admin
          - name: SPRING_DATA_MONGODB_DATABASE
            value: local
          - name: SPRING_DATA_MONGODB_USERNAME
            value: root
          - name: SPRING_DATA_MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: music-mongodb
                key: mongodb-root-password
      # imagePullSecrets:
      # - name: registry-credentials
