apiVersion: services.tanzu.vmware.com/v1
kind: ServiceBinding
metadata:
    name: music-14fc52
spec:
  alias: music
  serviceRef:
    apiGroup: bitnami.database.tanzu.vmware.com
    kind: MongoDBInstance
    name: music
  targetRef:
    apiGroup: apps.tanzu.vmware.com
    kind: ContainerApp
    name: mongo-music
